<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.1 (Python 3.8.2 on win32)" generated="20200512 13:10:23.779" rpa="false">
<suite id="s1" name="Formulario" source="C:\RobotFramework\CI\robotmobile\formulario.robot">
<test id="s1-t1" name="Cenário 01: Preencher formulario">
<kw name="Acesso Home" library="Home" type="setup">
<kw name="Open Application" library="AppiumLibrary">
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<arguments>
<arg>${REMOTE_URL}</arg>
<arg>platformName=${platformName}</arg>
<arg>deviceName=${deviceName}</arg>
<arg>udid=${dispositivo}</arg>
<arg>app=${aplicacao}</arg>
<arg>automationName=${automationName}</arg>
<arg>appPackage=${appPackage}</arg>
<arg>appActivity=${appActivity}</arg>
</arguments>
<msg timestamp="20200512 13:10:25.121" level="INFO">Could not connect to port 4723 on host 127.0.0.1</msg>
<msg timestamp="20200512 13:10:25.121" level="INFO">Could not get IP address for host: 127.0.0.1</msg>
<msg timestamp="20200512 13:10:27.124" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x03CD57C0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20200512 13:10:29.130" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x03CD5298&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20200512 13:10:31.138" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x03CD5868&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20200512 13:10:33.148" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20200512 13:10:33.146" endtime="20200512 13:10:33.148"></status>
</kw>
<msg timestamp="20200512 13:10:33.149" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20200512 13:10:33.569" level="FAIL">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x03CD5928&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</msg>
<status status="FAIL" starttime="20200512 13:10:24.114" endtime="20200512 13:10:33.569"></status>
</kw>
<status status="FAIL" starttime="20200512 13:10:24.114" endtime="20200512 13:10:33.570"></status>
</kw>
<kw name="Fechar Aplicacao" library="Home" type="teardown">
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20200512 13:10:33.573" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20200512 13:10:33.572" endtime="20200512 13:10:33.573"></status>
</kw>
<msg timestamp="20200512 13:10:33.574" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20200512 13:10:33.577" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20200512 13:10:33.571" endtime="20200512 13:10:33.577"></status>
</kw>
<kw name="Close Application" library="AppiumLibrary">
<doc>Closes the current application and also close webdriver session.</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20200512 13:10:33.579" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20200512 13:10:33.577" endtime="20200512 13:10:33.579"></status>
</kw>
<msg timestamp="20200512 13:10:33.580" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20200512 13:10:33.582" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20200512 13:10:33.577" endtime="20200512 13:10:33.582"></status>
</kw>
<status status="FAIL" starttime="20200512 13:10:33.571" endtime="20200512 13:10:33.582">Several failures occurred:

1) No application is open

2) No application is open</status>
</kw>
<status status="FAIL" starttime="20200512 13:10:24.113" endtime="20200512 13:10:33.583" critical="yes">Setup failed:
MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x03CD5928&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))

Also teardown failed:
Several failures occurred:

1) No application is open

2) No application is open</status>
</test>
<status status="FAIL" starttime="20200512 13:10:23.781" endtime="20200512 13:10:33.586"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Formulario">Formulario</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200512 13:10:27.124" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x03CD57C0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20200512 13:10:29.130" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x03CD5298&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20200512 13:10:31.138" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x03CD5868&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /wd/hub/session</msg>
<msg timestamp="20200512 13:10:33.149" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20200512 13:10:33.574" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20200512 13:10:33.580" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
